version: "3.4"
   
services:
  backend:
    container_name: tsl-wall-app-backend
    build: ./backend
    command: '/bin/bash -c "chmod +x /code/docker-entrypoint.sh && /code/docker-entrypoint.sh"'
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    expose:
      - '8000'
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  frontend:
    image: node:alpine
    container_name: tsl-wall-app-frontend
    env_file:  .env
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/home/app
    working_dir: /home/app
    command:  [sh, -c, "yarn && yarn start"]
    depends_on:
      - backend
    links:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s