version: "3.3"
   
services:
  backend:
    container_name: tsl-wall-app-backend
    build: ./backend
    command: '/bin/bash -c "chmod +x /code/docker-entrypoint.sh && /code/docker-entrypoint.sh"'
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    expose:
      - '8000'
    env_file: .env
  frontend:
    image: node:alpine
    container_name: tsl-wall-app-frontend
    env_file:  .env
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/home/app
    working_dir: /home/app
    command:  [sh, -c, "yarn && yarn start"]
    links:
      - backend
    restart: 'no'
 